# Generated by Django 5.2 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acquaiolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("telefono", models.CharField(max_length=32)),
                (
                    "zona_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Identificativo della Zona acquaiolo nel KML.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Acquaiolo",
                "verbose_name_plural": "Acquaioli",
                "ordering": ["nome", "id"],
            },
        ),
    ]
