# Generated by Django 5.2.17 on 2026-09-24 09:21

import django.db.models.deletion
import segnalazioni.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segnalazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_pratica', models.CharField(default=segnalazioni.models.generate_codice_pratica, max_length=15, unique=True)),
                ('token_stato', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stato_corrente', models.CharField(choices=[('ricevuta', 'Ricevuta'), ('in_verifica', 'In verifica'), ('assegnata', 'Assegnata'), ('in_intervento', 'In intervento'), ('chiusa', 'Chiusa')], default='ricevuta', max_length=20)),
                ('priorita', models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='bassa', max_length=10)),
                ('priorita_calcolata', models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='bassa', max_length=10)),
                ('override_motivazione', models.TextField(blank=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('descrizione', models.TextField()),
                ('cellulare', models.CharField(max_length=20)),
                ('is_duplicato', models.BooleanField(default=False)),
                ('messaggio_al_segnalante', models.TextField(blank=True)),
                ('transcript_ai', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('durata', models.CharField(blank=True, max_length=100)),
                ('quantita_acqua', models.CharField(blank=True, max_length=100)),
                ('pericolo_persone', models.CharField(blank=True, default='', max_length=20)),
                ('pericolo_strada', models.CharField(blank=True, default='', max_length=20)),
                ('pericolo_edifici', models.CharField(blank=True, default='', max_length=20)),
                ('estratti_confidenza', models.JSONField(blank=True, default=dict)),
                ('layer', models.CharField(blank=True, choices=[('canale', 'Canale'), ('condotta', 'Condotta'), ('reticolo_principale', 'Reticolo Idrico Principale')], default='', max_length=20)),
                ('id_placemark', models.CharField(blank=True, default='', max_length=50)),
                ('nome_tracciato', models.CharField(blank=True, default='', max_length=255)),
                ('nome_completo_tracciato', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_tracciato', models.CharField(blank=True, default='', max_length=100)),
                ('distanza_m', models.FloatField(blank=True, null=True)),
                ('zona_id', models.IntegerField(blank=True, null=True)),
                ('acquaiolo_competente_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='segnalazioni/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segnalazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='segnalazioni.segnalazione')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('ricevuta', 'Ricevuta'), ('in_verifica', 'In verifica'), ('assegnata', 'Assegnata'), ('in_intervento', 'In intervento'), ('chiusa', 'Chiusa')], max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segnalazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='segnalazioni.segnalazione')),
            ],
        ),
    ]
