# Generated by Django 5.2.17 on 2026-09-24 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnalazioni', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='operatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(default='cambio_stato', max_length=50),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='duplicato_di',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicati', to='segnalazioni.segnalazione'),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='esito',
            field=models.CharField(blank=True, choices=[('risolta', 'Risolta'), ('duplicata', 'Duplicata'), ('non_di_competenza', 'Non di competenza'), ('non_riscontrata', 'Non riscontrata'), ('falsa', 'Falsa')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='operatore_riferimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='stato',
            field=models.CharField(max_length=50),
        ),
    ]
