# Generated by Django 5.2.17 on 2026-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnalazioni', '0002_evento_operatore_evento_tipo_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazione',
            name='categoria_originale',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='lat_originale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='lng_originale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
