# Generated by Django 5.2.17 on 2026-09-24 16:30

from django.db import migrations, models

# Durate tolte nella Revisione delle opzioni (#100). La priorità calcolata non cambia:
# la durata non entra nel calcolo.
DURATE_TOLTE = {"meno_di_un_ora": "adesso", "non_applicabile": ""}


def aggiorna_durate(apps, schema_editor):
    Segnalazione = apps.get_model("segnalazioni", "Segnalazione")
    for vecchia, nuova in DURATE_TOLTE.items():
        Segnalazione.objects.filter(durata=vecchia).update(durata=nuova)


class Migration(migrations.Migration):

    dependencies = [
        ('segnalazioni', '0003_segnalazione_categoria_originale_and_more'),
    ]

    operations = [
        migrations.RunPython(aggiorna_durate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='segnalazione',
            name='categoria',
            field=models.CharField(blank=True, choices=[('acqua_che_affiora', 'Acqua che esce dal terreno'), ('perdita_dal_canale', 'Canale che perde'), ('canale_che_tracima', 'Canale che esonda o allaga'), ('argine_danneggiato', 'Argine o sponda franata'), ('ostruzione', "Qualcosa blocca l'acqua"), ('canale_asciutto', "Canale senz'acqua"), ('paratoia_danneggiata', 'Paratoia o impianto rotto'), ('acqua_sporca', 'Acqua sporca o rifiuti'), ('altro', 'Altro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='categoria_originale',
            field=models.CharField(blank=True, choices=[('acqua_che_affiora', 'Acqua che esce dal terreno'), ('perdita_dal_canale', 'Canale che perde'), ('canale_che_tracima', 'Canale che esonda o allaga'), ('argine_danneggiato', 'Argine o sponda franata'), ('ostruzione', "Qualcosa blocca l'acqua"), ('canale_asciutto', "Canale senz'acqua"), ('paratoia_danneggiata', 'Paratoia o impianto rotto'), ('acqua_sporca', 'Acqua sporca o rifiuti'), ('altro', 'Altro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='durata',
            field=models.CharField(blank=True, choices=[('adesso', "L'ho appena notato"), ('alcune_ore', 'Da qualche ora'), ('piu_di_un_giorno', 'Da qualche giorno'), ('da_settimane', 'Da settimane'), ('non_so', 'Non so')], max_length=100),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='pericolo_edifici',
            field=models.CharField(blank=True, choices=[('si', 'Sì'), ('no', 'No'), ('non_so', 'Non so')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='pericolo_persone',
            field=models.CharField(blank=True, choices=[('si', 'Sì'), ('no', 'No'), ('non_so', 'Non so')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='pericolo_strada',
            field=models.CharField(blank=True, choices=[('si', 'Sì'), ('no', 'No'), ('non_so', 'Non so')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='quantita_acqua',
            field=models.CharField(blank=True, choices=[('gocce', 'Gocciola'), ('piccolo_flusso', 'Un filo, come un rubinetto'), ('molta_acqua', 'Tanta, scorre forte'), ('getto', 'Zampilla con forza'), ('non_so', 'Non so'), ('non_applicabile', 'Non applicabile')], max_length=100),
        ),
    ]
