# Generated by Django 5.2.17 on 2026-09-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnalazioni', '0003_segnalazione_categoria_originale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazione',
            name='comune',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
