# Generated by Django 5.2.17 on 2026-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnalazioni', '0005_nuove_opzioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='segnalazione',
            name='canale_ingresso',
            field=models.CharField(choices=[('web_app', 'Web app'), ('numero_verde', 'Numero verde'), ('email', 'Email'), ('di_persona', 'Di persona')], default='web_app', max_length=20),
        ),
    ]
