/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/perimetro/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Controllo perimetro (App) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lat: number;
                        lng: number;
                    };
                };
            };
            responses: {
                /** @description Esito del controllo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accettato: boolean;
                            distanza_m: number;
                            zona_id?: number;
                            messaggio: string;
                        };
                    };
                };
                /** @description Coordinate mancanti, non numeriche o fuori range (`lat` tra -90 e 90, `lng` tra -180 e 180) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layer/{layer}.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Layer GeoJSON del Reticolo consortile e delle Zone acquaiolo (App e Portale operatore)
         * @description Layer statico per disegnare la mappa con Leaflet. Le geometrie sono semplificate e servono solo al disegno.
         */
        get: operations["layerGeoJSON"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estrazione/vocale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estrazione strutturata da audio (App) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Registrazione di MediaRecorder o file audio, al massimo 10 MB. Formati:
                         *     `audio/webm`, `audio/ogg`, `audio/mp4`, `audio/m4a`, `audio/x-m4a`, `audio/aac`,
                         *     `audio/mpeg`, `audio/mp3`, `audio/wav`, `audio/x-wav`, `audio/flac`
                         *     (parametri come `;codecs=opus` ammessi).
                         */
                        audio: string;
                    };
                };
            };
            responses: {
                /**
                 * @description Dati estratti. In `campi` ci sono solo i campi detti dal Segnalante; quelli non
                 *     detti sono in `mancanti`, da compilare a mano nel form.
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            transcript: string;
                            campi: {
                                /** @enum {string} */
                                categoria?: "acqua_che_affiora" | "perdita_dal_canale" | "canale_che_tracima" | "argine_danneggiato" | "ostruzione" | "canale_asciutto" | "paratoia_danneggiata" | "acqua_sporca" | "altro";
                                descrizione?: string;
                                /** @enum {string} */
                                durata?: "adesso" | "alcune_ore" | "piu_di_un_giorno" | "da_settimane" | "non_so";
                                /**
                                 * @description non_applicabile se la categoria non prevede la domanda sulla quantità d'acqua.
                                 * @enum {string}
                                 */
                                quantita_acqua?: "gocce" | "piccolo_flusso" | "molta_acqua" | "getto" | "non_so" | "non_applicabile";
                                /** @enum {string} */
                                pericolo_persone?: "si" | "no" | "non_so";
                                /** @enum {string} */
                                pericolo_strada?: "si" | "no" | "non_so";
                                /** @enum {string} */
                                pericolo_edifici?: "si" | "no" | "non_so";
                            };
                            mancanti: ("categoria" | "descrizione" | "durata" | "quantita_acqua" | "pericolo_persone" | "pericolo_strada" | "pericolo_edifici")[];
                        };
                    };
                };
                /** @description Audio mancante, vuoto o in un formato non supportato */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Audio oltre i 10 MB */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Assistente vocale non disponibile (provider che non risponde o non configurato); il Segnalante compila il form a mano */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estrazione/foto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Controllo di pertinenza ed estrazione dalla foto (App)
         * @description L'App lo chiama subito dopo lo scatto. Se la foto non è pertinente al reticolo
         *     consortile va scartata e rifatta. Se è pertinente, i `campi` visti nella foto
         *     completano quelli che il Segnalante non dice a voce o non sceglie a mano; quello che
         *     dice il Segnalante ha sempre la precedenza.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description La foto del problema, al massimo 10 MB. Formati: `image/jpeg`, `image/png`,
                         *     `image/webp`, `image/heic`, `image/heif`.
                         */
                        foto: string;
                    };
                };
            };
            responses: {
                /**
                 * @description Esito dell'analisi. In `campi` ci sono solo i campi che si vedono con sicurezza
                 *     nella foto; se la foto non è pertinente `campi` è vuoto e `motivo` spiega al
                 *     Segnalante cosa fotografare.
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pertinente: boolean;
                            /** @description Messaggio per il Segnalante se la foto non è pertinente, altrimenti null. */
                            motivo: string | null;
                            /**
                             * @description La durata non si ricava da una foto; un pericolo compare solo quando si
                             *     vede (una foto non basta a escluderlo).
                             */
                            campi: {
                                /** @enum {string} */
                                categoria?: "acqua_che_affiora" | "perdita_dal_canale" | "canale_che_tracima" | "argine_danneggiato" | "ostruzione" | "canale_asciutto" | "paratoia_danneggiata" | "acqua_sporca" | "altro";
                                descrizione?: string;
                                /** @enum {string} */
                                quantita_acqua?: "gocce" | "piccolo_flusso" | "molta_acqua" | "getto";
                                /** @enum {string} */
                                pericolo_strada?: "si";
                                /** @enum {string} */
                                pericolo_edifici?: "si";
                            };
                        };
                    };
                };
                /** @description Foto mancante, vuota o in un formato non supportato */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Foto oltre i 10 MB */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Analisi non disponibile (provider che non risponde o non configurato); l'App tiene la foto senza analisi */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segnalazioni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista segnalazioni (Portale operatore) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: Record<string, never>[];
                            total?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Invio della segnalazione (App) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        lat: number;
                        lng: number;
                        /** Format: binary */
                        foto: string;
                        descrizione: string;
                        cellulare: string;
                        transcript_ai?: string;
                        /** @enum {string} */
                        categoria?: "acqua_che_affiora" | "perdita_dal_canale" | "canale_che_tracima" | "argine_danneggiato" | "ostruzione" | "canale_asciutto" | "paratoia_danneggiata" | "acqua_sporca" | "altro";
                        /** @enum {string} */
                        durata?: "adesso" | "alcune_ore" | "piu_di_un_giorno" | "da_settimane" | "non_so";
                        /**
                         * @description Si chiede solo per acqua_che_affiora, perdita_dal_canale, canale_che_tracima e
                         *     argine_danneggiato; per le altre categorie vale non_applicabile.
                         * @enum {string}
                         */
                        quantita_acqua?: "gocce" | "piccolo_flusso" | "molta_acqua" | "getto" | "non_so" | "non_applicabile";
                        /** @enum {string} */
                        pericolo_persone?: "si" | "no" | "non_so";
                        /** @enum {string} */
                        pericolo_strada?: "si" | "no" | "non_so";
                        /** @enum {string} */
                        pericolo_edifici?: "si" | "no" | "non_so";
                        /** @description Confidenza dell'estrazione vocale per campo (JSON string) */
                        estratti_confidenza?: string;
                    };
                };
            };
            responses: {
                /** @description Segnalazione creata */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            codice_pratica: string;
                            token_stato: string;
                            priorita: string;
                            pericolo_immediato: boolean;
                        };
                    };
                };
                /** @description Errore validazione o fuori perimetro */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segnalazioni/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * Scheda della segnalazione con il Registro (Portale operatore)
         * @description Aprire la scheda non cambia lo Stato.
         */
        get: operations["dettaglioSegnalazione"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correzioni dell'Operatore sul campo (Portale operatore)
         * @description Si mandano solo i campi da correggere. Ogni correzione scrive un evento
         *     `correzione_campo` nel Registro.
         *
         *     - **Posizione** (`lat` e `lng` insieme): alla prima correzione si conserva quella
         *       inviata in `lat_originale`/`lng_originale`. Si ricalcolano tracciato più vicino,
         *       distanza e `zona_id`; `acquaiolo_competente_id` si imposta solo se è vuoto, un
         *       Acquaiolo già scelto non si sostituisce. Lo spostamento fuori perimetro è ammesso:
         *       per avvisare l'Operatore il Portale chiama prima `/perimetro/check`.
         *     - **Categoria**: alla prima correzione si conserva quella inviata in
         *       `categoria_originale`. Non ricalcola la priorità.
         *     - **Priorità**: `override_motivazione` è obbligatoria quando `priorita` è diversa da
         *       `priorita_calcolata`.
         *     - **Acquaiolo**: cambia l'Acquaiolo competente senza cambiare lo Stato.
         */
        patch: operations["correggiSegnalazione"];
        trace?: never;
    };
    "/segnalazioni/{id}/azioni": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Azioni dell'Operatore sulla segnalazione (Portale operatore)
         * @description Ogni azione scrive un evento nel Registro con l'Operatore autenticato e la `nota`.
         *
         *     | `azione` | Da | A | Campi obbligatori |
         *     |---|---|---|---|
         *     | `prendi_in_carico` | ricevuta | in_verifica | — (diventa Operatore di riferimento) |
         *     | `assegna` | in_verifica | assegnata | `acquaiolo_id` |
         *     | `avvia_intervento` | assegnata | in_intervento | — |
         *     | `chiudi` | qualunque tranne chiusa | chiusa | `esito`; `duplicato_di` se l'esito è `duplicata` |
         *     | `indietro` | in_verifica, assegnata, in_intervento | lo Stato precedente | `nota` |
         *     | `riapri` | chiusa | in_verifica | `nota` |
         *     | `nota` | qualunque | invariato | `nota` (nota interna) |
         *     | `messaggio_segnalante` | qualunque | invariato | `nota` (il testo che compare nella Pagina di stato) |
         *
         *     Chiudere come `duplicata` scrive anche un evento `duplicato_collegato` nel Registro
         *     dell'originale.
         */
        post: operations["azioneSegnalazione"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segnalazioni/stato/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pagina di stato pubblica (App/Web) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stato per il segnalante */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SegnalazioneStatoPubblico"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (Portale operatore) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Tokens JWT */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access: string;
                            refresh: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh del token (Portale operatore) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh: string;
                    };
                };
            };
            responses: {
                /** @description Nuovo Access Token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info operatore corrente (Portale operatore) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operatore loggato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            nome_completo: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout con blacklist (Portale operatore) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh: string;
                    };
                };
            };
            responses: {
                /** @description Logout effettuato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/push-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chiave pubblica per le notifiche push */
        get: operations["chiavePush"];
        put?: never;
        /** Registra il dispositivo dell'operatore per le notifiche push */
        post: operations["registraPush"];
        /** Disattiva le notifiche push sul dispositivo corrente */
        delete: operations["eliminaPush"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acquaioli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista della Rubrica acquaioli (Portale operatore) */
        get: operations["listaAcquaioli"];
        put?: never;
        /** Crea un Acquaiolo nella Rubrica (Portale operatore) */
        post: operations["creaAcquaiolo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acquaioli/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifica un Acquaiolo nella Rubrica (Portale operatore) */
        patch: operations["modificaAcquaiolo"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example fuori_perimetro */
            code: string;
            /** @example Il punto indicato è troppo distante dal reticolo consortile. */
            message: string;
            fields: {
                [key: string]: string[];
            };
        };
        /**
         * @description Quello che vede chi ha il link della Pagina di stato, senza login. Oltre allo Stato
         *     c'è un riassunto della Segnalazione (codice, foto, categoria, luogo, data d'invio)
         *     per riconoscerla quando si riapre il link. Il cellulare e la descrizione non ci sono.
         */
        SegnalazioneStatoPubblico: {
            codice_pratica: string;
            /**
             * Format: date-time
             * @description Data d'invio.
             */
            created_at: string;
            /** @description Le foto inviate. Chiunque abbia il token le può vedere: gli URL si aprono senza JWT. */
            foto: string[];
            /**
             * @description La categoria attuale, anche se l'Operatore l'ha corretta. Vuota se non indicata.
             * @enum {string}
             */
            categoria: "acqua_che_affiora" | "perdita_dal_canale" | "canale_che_tracima" | "argine_danneggiato" | "ostruzione" | "canale_asciutto" | "paratoia_danneggiata" | "acqua_sporca" | "altro" | "";
            /** @description Il comune del punto segnalato. Vuoto se non si riesce a ricavarlo. */
            comune: string;
            /** @description Il tracciato più vicino, come nella scheda del Portale operatore. */
            nome_completo_tracciato: string;
            /** @enum {string} */
            stato_corrente: "ricevuta" | "in_verifica" | "assegnata" | "in_intervento" | "chiusa";
            is_duplicato: boolean;
            messaggio_al_segnalante?: string;
            timeline: {
                stato?: string;
                /** Format: date-time */
                data?: string;
            }[];
        };
        /** @enum {string} */
        Stato: "ricevuta" | "in_verifica" | "assegnata" | "in_intervento" | "chiusa";
        /** @enum {string} */
        Priorita: "bassa" | "media" | "alta" | "critica";
        /** @enum {string} */
        Esito: "risolta" | "duplicata" | "non_di_competenza" | "non_riscontrata" | "falsa";
        Operatore: {
            id: number;
            /** @example Mario Rossi */
            nome_completo: string;
        };
        /** @description Una voce del Registro. Il Registro si aggiunge e basta. */
        Evento: {
            id: number;
            /** @enum {string} */
            tipo_evento: "cambio_stato" | "correzione_campo" | "nota" | "duplicato_collegato";
            /** @description Lo Stato della Segnalazione dopo l'evento. */
            stato: components["schemas"]["Stato"];
            /** @description Null per l'evento `ricevuta` scritto all'invio. */
            operatore: components["schemas"]["Operatore"] | null;
            /** @description Vuota se l'Operatore non l'ha scritta. Per `correzione_campo` elenca i campi modificati. */
            nota: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Una Segnalazione chiusa con esito `duplicata` e collegata a questa. */
        DuplicatoCollegato: {
            id: number;
            codice_pratica: string;
            cellulare: string;
            foto: string[];
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description La scheda della Segnalazione nel Portale operatore. I campi testuali non compilati
         *     sono stringhe vuote; quelli numerici o i collegamenti non presenti sono `null`.
         */
        SegnalazioneDettaglio: {
            id: number;
            codice_pratica: string;
            stato_corrente: components["schemas"]["Stato"];
            /**
             * @description Vuoto finché la Segnalazione non è Chiusa.
             * @enum {string}
             */
            esito: "risolta" | "duplicata" | "non_di_competenza" | "non_riscontrata" | "falsa" | "";
            priorita: components["schemas"]["Priorita"];
            /** @description La priorità calcolata all'invio; resta invariata se l'Operatore la cambia. */
            priorita_calcolata: components["schemas"]["Priorita"];
            /** @description Perché l'Operatore ha cambiato la priorità calcolata. Vuota se non l'ha cambiata. */
            override_motivazione: string;
            /** Format: date-time */
            created_at: string;
            lat: number;
            lng: number;
            /** @description Posizione GPS inviata dal Segnalante, conservata alla prima correzione. Null se mai corretta. */
            lat_originale: number | null;
            lng_originale: number | null;
            descrizione: string;
            cellulare: string;
            transcript_ai: string;
            foto: string[];
            /** @enum {string} */
            categoria: "acqua_che_affiora" | "perdita_dal_canale" | "canale_che_tracima" | "argine_danneggiato" | "ostruzione" | "canale_asciutto" | "paratoia_danneggiata" | "acqua_sporca" | "altro" | "";
            /**
             * @description Categoria inviata, conservata alla prima correzione. Vuota se mai corretta.
             * @enum {string}
             */
            categoria_originale: "acqua_che_affiora" | "perdita_dal_canale" | "canale_che_tracima" | "argine_danneggiato" | "ostruzione" | "canale_asciutto" | "paratoia_danneggiata" | "acqua_sporca" | "altro" | "";
            /** @enum {string} */
            durata: "adesso" | "alcune_ore" | "piu_di_un_giorno" | "da_settimane" | "non_so" | "";
            /** @enum {string} */
            quantita_acqua: "gocce" | "piccolo_flusso" | "molta_acqua" | "getto" | "non_so" | "non_applicabile" | "";
            /** @enum {string} */
            pericolo_persone: "si" | "no" | "non_so" | "";
            /** @enum {string} */
            pericolo_strada: "si" | "no" | "non_so" | "";
            /** @enum {string} */
            pericolo_edifici: "si" | "no" | "non_so" | "";
            /** @description Confidenza dell'estrazione vocale per campo, da 0 a 1. Vuoto se il form è stato compilato a mano. */
            estratti_confidenza: {
                [key: string]: number;
            };
            /**
             * @description Layer del tracciato più vicino.
             * @enum {string}
             */
            layer: "canale" | "condotta" | "reticolo_principale" | "";
            nome_tracciato: string;
            nome_completo_tracciato: string;
            tipo_tracciato: string;
            /** @description Distanza dal tracciato più vicino. */
            distanza_m: number | null;
            /** @description Zona acquaiolo in cui cade la posizione. */
            zona_id: number | null;
            /** @description Id dell'Acquaiolo nella Rubrica acquaioli (`/acquaioli`), da cui si prende il telefono. */
            acquaiolo_competente_id: number | null;
            operatore_riferimento: components["schemas"]["Operatore"] | null;
            is_duplicato: boolean;
            /** @description Id dell'originale, se questa Segnalazione è un Duplicato. */
            duplicato_di: number | null;
            /** @description I Duplicati collegati a questa Segnalazione ("segnalata anche da N persone"). */
            duplicati: components["schemas"]["DuplicatoCollegato"][];
            messaggio_al_segnalante: string;
            /** @description In ordine cronologico, dal più vecchio. */
            registro: components["schemas"]["Evento"][];
        };
        Acquaiolo: {
            readonly id: number;
            /** @example BRIGNANI */
            nome: string;
            /** @example +39 333 7654321 */
            telefono: string;
            /**
             * @description Identificativo della Zona acquaiolo nel KML.
             * @example 21
             */
            zona_id: number | null;
        };
        AcquaioloInput: {
            nome: string;
            telefono: string;
            zona_id?: number | null;
        };
        /** @description Un tracciato del Reticolo consortile (layer `canale`, `condotta`, `reticolo_principale`). */
        FeatureTracciato: {
            /** @constant */
            type: "Feature";
            /**
             * @description Id del placemark nel KML.
             * @example RIB_Canali_2026.68
             */
            id: string;
            properties: {
                nome: string;
                nome_completo: string;
                tipo: string | null;
                codice: string | null;
            };
            geometry: {
                /** @enum {string} */
                type: "LineString" | "MultiLineString";
                /** @description Coordinate `[lng, lat]` in WGS84, semplificate a 5 m. */
                coordinates: unknown[];
            };
        };
        /** @description Una Zona acquaiolo (layer `zona_acquaiolo`). */
        FeatureZonaAcquaiolo: {
            /** @constant */
            type: "Feature";
            /**
             * @description Lo stesso `zona_id` di `/perimetro/check` e della Rubrica acquaioli.
             * @example 19
             */
            id: number;
            properties: {
                /** @description Macro-zona. */
                nome: string;
                servita: boolean;
                /** @description Null se la zona è `NON SERVITA`. */
                acquaiolo: string | null;
            };
            geometry: {
                /** @enum {string} */
                type: "Polygon" | "MultiPolygon";
                /** @description Coordinate `[lng, lat]` in WGS84, semplificate a 5 m. */
                coordinates: unknown[];
            };
        };
        LayerGeoJSON: {
            /** @constant */
            type: "FeatureCollection";
            features: (components["schemas"]["FeatureTracciato"] | components["schemas"]["FeatureZonaAcquaiolo"])[];
        };
    };
    responses: {
        /** @description Token mancante, scaduto o non valido */
        NonAutenticato: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Nessuna Segnalazione con questo id */
        SegnalazioneNonTrovata: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    layerGeoJSON: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer: "canale" | "condotta" | "reticolo_principale" | "zona_acquaiolo";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FeatureCollection del layer */
            200: {
                headers: {
                    /** @example public, max-age=86400 */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["LayerGeoJSON"];
                };
            };
            /** @description Layer inesistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dettaglioSegnalazione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La Segnalazione */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegnalazioneDettaglio"];
                };
            };
            401: components["responses"]["NonAutenticato"];
            404: components["responses"]["SegnalazioneNonTrovata"];
        };
    };
    correggiSegnalazione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    lat?: number;
                    lng?: number;
                    /** @enum {string} */
                    categoria?: "acqua_che_affiora" | "perdita_dal_canale" | "canale_che_tracima" | "argine_danneggiato" | "ostruzione" | "canale_asciutto" | "paratoia_danneggiata" | "acqua_sporca" | "altro";
                    priorita?: components["schemas"]["Priorita"];
                    override_motivazione?: string;
                    acquaiolo_competente_id?: number | null;
                };
            };
        };
        responses: {
            /** @description La Segnalazione dopo la correzione */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegnalazioneDettaglio"];
                };
            };
            /** @description Dati non validi (per esempio priorità cambiata senza motivazione) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["NonAutenticato"];
            404: components["responses"]["SegnalazioneNonTrovata"];
        };
    };
    azioneSegnalazione: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    azione: "prendi_in_carico" | "assegna" | "avvia_intervento" | "chiudi" | "indietro" | "riapri" | "nota" | "messaggio_segnalante";
                    nota?: string;
                    /** @description Id dell'Acquaiolo nella Rubrica acquaioli. */
                    acquaiolo_id?: number;
                    esito?: components["schemas"]["Esito"];
                    /** @description Id della Segnalazione originale. */
                    duplicato_di?: number;
                };
            };
        };
        responses: {
            /** @description La Segnalazione dopo l'azione */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegnalazioneDettaglio"];
                };
            };
            /** @description Azione sconosciuta o campo obbligatorio mancante */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["NonAutenticato"];
            404: components["responses"]["SegnalazioneNonTrovata"];
            /** @description Azione non ammessa nello Stato attuale (per esempio `avvia_intervento` su una Segnalazione Ricevuta) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    chiavePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configurazione push */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        public_key: string;
                    };
                };
            };
        };
    };
    registraPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    endpoint: string;
                    p256dh: string;
                    auth: string;
                };
            };
        };
        responses: {
            /** @description Dispositivo registrato */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    eliminaPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    endpoint: string;
                };
            };
        };
        responses: {
            /** @description Dispositivo disattivato */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listaAcquaioli: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Elenco degli Acquaioli */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acquaiolo"][];
                };
            };
            /** @description Autenticazione richiesta */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    creaAcquaiolo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcquaioloInput"];
            };
        };
        responses: {
            /** @description Acquaiolo creato */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acquaiolo"];
                };
            };
            /** @description Dati non validi */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Autenticazione richiesta */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    modificaAcquaiolo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome?: string;
                    telefono?: string;
                    zona_id?: number | null;
                };
            };
        };
        responses: {
            /** @description Acquaiolo aggiornato */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acquaiolo"];
                };
            };
            /** @description Dati non validi */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Autenticazione richiesta */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
