/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/perimetro/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Controllo perimetro (App) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lat: number;
                        lng: number;
                    };
                };
            };
            responses: {
                /** @description Esito del controllo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accettato: boolean;
                            distanza_m: number;
                            zona_id?: number;
                            messaggio: string;
                        };
                    };
                };
                /** @description Coordinate mancanti, non numeriche o fuori range (`lat` tra -90 e 90, `lng` tra -180 e 180) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layer/{layer}.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Layer GeoJSON del Reticolo consortile e delle Zone acquaiolo (App e Portale operatore)
         * @description Layer statico per disegnare la mappa con Leaflet. Le geometrie sono semplificate e servono solo al disegno.
         */
        get: operations["layerGeoJSON"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estrazione/vocale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estrazione strutturata da audio (App) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Registrazione di MediaRecorder o file audio, al massimo 10 MB. Formati:
                         *     `audio/webm`, `audio/ogg`, `audio/mp4`, `audio/m4a`, `audio/x-m4a`, `audio/aac`,
                         *     `audio/mpeg`, `audio/mp3`, `audio/wav`, `audio/x-wav`, `audio/flac`
                         *     (parametri come `;codecs=opus` ammessi).
                         */
                        audio: string;
                    };
                };
            };
            responses: {
                /**
                 * @description Dati estratti. In `campi` ci sono solo i campi detti dal Segnalante; quelli non
                 *     detti sono in `mancanti`, da compilare a mano nel form.
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            transcript: string;
                            campi: {
                                /** @enum {string} */
                                categoria?: "acqua_che_affiora" | "canale_che_tracima" | "argine_danneggiato" | "ostruzione" | "paratoia_danneggiata" | "acqua_sporca" | "altro";
                                descrizione?: string;
                                /** @enum {string} */
                                durata?: "adesso" | "meno_di_un_ora" | "alcune_ore" | "piu_di_un_giorno" | "non_so" | "non_applicabile";
                                /** @enum {string} */
                                quantita_acqua?: "gocce" | "piccolo_flusso" | "molta_acqua" | "non_so" | "non_applicabile";
                                /** @enum {string} */
                                pericolo_persone?: "si" | "no" | "non_so";
                                /** @enum {string} */
                                pericolo_strada?: "si" | "no" | "non_so";
                                /** @enum {string} */
                                pericolo_edifici?: "si" | "no" | "non_so";
                            };
                            mancanti: ("categoria" | "descrizione" | "durata" | "quantita_acqua" | "pericolo_persone" | "pericolo_strada" | "pericolo_edifici")[];
                        };
                    };
                };
                /** @description Audio mancante, vuoto o in un formato non supportato */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Audio oltre i 10 MB */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Assistente vocale non disponibile (provider che non risponde o non configurato); il Segnalante compila il form a mano */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segnalazioni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista segnalazioni (Portale operatore) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: Record<string, never>[];
                            total?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Invio della segnalazione (App) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        lat: number;
                        lng: number;
                        /** Format: binary */
                        foto: string;
                        descrizione: string;
                        cellulare: string;
                        transcript_ai?: string;
                    };
                };
            };
            responses: {
                /** @description Segnalazione creata */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            codice_pratica: string;
                            token_stato: string;
                            priorita: string;
                            pericolo_immediato: boolean;
                        };
                    };
                };
                /** @description Errore validazione o fuori perimetro */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segnalazioni/stato/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pagina di stato pubblica (App/Web) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stato per il segnalante */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SegnalazioneStatoPubblico"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (Portale operatore) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Tokens JWT */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access: string;
                            refresh: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh del token (Portale operatore) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh: string;
                    };
                };
            };
            responses: {
                /** @description Nuovo Access Token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info operatore corrente (Portale operatore) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operatore loggato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            nome_completo: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout con blacklist (Portale operatore) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh: string;
                    };
                };
            };
            responses: {
                /** @description Logout effettuato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acquaioli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista della Rubrica acquaioli (Portale operatore) */
        get: operations["listaAcquaioli"];
        put?: never;
        /** Crea un Acquaiolo nella Rubrica (Portale operatore) */
        post: operations["creaAcquaiolo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acquaioli/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifica un Acquaiolo nella Rubrica (Portale operatore) */
        patch: operations["modificaAcquaiolo"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example fuori_perimetro */
            code: string;
            /** @example Il punto indicato è troppo distante dal reticolo consortile. */
            message: string;
            fields: {
                [key: string]: string[];
            };
        };
        SegnalazioneStatoPubblico: {
            /** @enum {string} */
            stato_corrente: "ricevuta" | "in_verifica" | "assegnata" | "in_intervento" | "chiusa";
            is_duplicato: boolean;
            messaggio_al_segnalante?: string;
            timeline: {
                stato?: string;
                /** Format: date-time */
                data?: string;
            }[];
        };
        Acquaiolo: {
            readonly id: number;
            /** @example BRIGNANI */
            nome: string;
            /** @example +39 333 7654321 */
            telefono: string;
            /**
             * @description Identificativo della Zona acquaiolo nel KML.
             * @example 21
             */
            zona_id: number | null;
        };
        AcquaioloInput: {
            nome: string;
            telefono: string;
            zona_id?: number | null;
        };
        /** @description Un tracciato del Reticolo consortile (layer `canale`, `condotta`, `reticolo_principale`). */
        FeatureTracciato: {
            /** @constant */
            type: "Feature";
            /**
             * @description Id del placemark nel KML.
             * @example RIB_Canali_2026.68
             */
            id: string;
            properties: {
                nome: string;
                nome_completo: string;
                tipo: string | null;
                codice: string | null;
            };
            geometry: {
                /** @enum {string} */
                type: "LineString" | "MultiLineString";
                /** @description Coordinate `[lng, lat]` in WGS84, semplificate a 5 m. */
                coordinates: unknown[];
            };
        };
        /** @description Una Zona acquaiolo (layer `zona_acquaiolo`). */
        FeatureZonaAcquaiolo: {
            /** @constant */
            type: "Feature";
            /**
             * @description Lo stesso `zona_id` di `/perimetro/check` e della Rubrica acquaioli.
             * @example 19
             */
            id: number;
            properties: {
                /** @description Macro-zona. */
                nome: string;
                servita: boolean;
                /** @description Null se la zona è `NON SERVITA`. */
                acquaiolo: string | null;
            };
            geometry: {
                /** @enum {string} */
                type: "Polygon" | "MultiPolygon";
                /** @description Coordinate `[lng, lat]` in WGS84, semplificate a 5 m. */
                coordinates: unknown[];
            };
        };
        LayerGeoJSON: {
            /** @constant */
            type: "FeatureCollection";
            features: (components["schemas"]["FeatureTracciato"] | components["schemas"]["FeatureZonaAcquaiolo"])[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    layerGeoJSON: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer: "canale" | "condotta" | "reticolo_principale" | "zona_acquaiolo";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FeatureCollection del layer */
            200: {
                headers: {
                    /** @example public, max-age=86400 */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["LayerGeoJSON"];
                };
            };
            /** @description Layer inesistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listaAcquaioli: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Elenco degli Acquaioli */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acquaiolo"][];
                };
            };
            /** @description Autenticazione richiesta */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    creaAcquaiolo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcquaioloInput"];
            };
        };
        responses: {
            /** @description Acquaiolo creato */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acquaiolo"];
                };
            };
            /** @description Dati non validi */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Autenticazione richiesta */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    modificaAcquaiolo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome?: string;
                    telefono?: string;
                    zona_id?: number | null;
                };
            };
        };
        responses: {
            /** @description Acquaiolo aggiornato */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acquaiolo"];
                };
            };
            /** @description Dati non validi */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Autenticazione richiesta */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
